### ISSUE TITLE
Mlab-ns will throws an internal server error

### ISSUE THREAD

**Issue by hellais** [m-lab/ooni-support#72]
This does not happen all the time and usually if I reload the resource it will not throw the error message again, but it still is probably something worthwhile investigating.

Doing a `GET` request to `http://mlab-nstesting.appspot.com/ooni`, you get:

```
Internal Server Error

The server has either erred or is incapable of performing the requested operation.

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~mlab-nstesting/1.378318471317236039/mlabns/handlers/lookup.py", line 50, in get
    self.send_json_response(sliver_tools, query)
  File "/base/data/home/apps/s~mlab-nstesting/1.378318471317236039/mlabns/handlers/lookup.py", line 157, in send_json_response
    if sliver_tool.tool_extra and tool.show_tool_extra:
AttributeError: 'NoneType' object has no attribute 'show_tool_extra'

```

**Comment by mtlynch** [comment]
I've confirmed this is a bug in mlab-ns. I've filed it here https://code.google.com/p/m-lab/issues/detail?id=40

**Comment by hawkinswnaf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

And I updated that bug report with some of my findings.

On 04/22/2015 03:03 PM, mtlynch wrote:
> I've confirmed this is a bug in mlab-ns. I've filed it here
> https://code.google.com/p/m-lab/issues/detail?id=40
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/m-lab-tools/ooni-support/issues/72#issuecomment-953
05774
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

iQIcBAEBAgAGBQJVODjJAAoJEPwC0mkexjE/8B4P/1DBAB6L4Pa5v0aHxQsxwwwT
a8PKr07VnKgsz1wg/qgIiSW4B4+p7XYFgx70yup8a39QfYyBFnAEbNLqo0oHq9vq
5UKdt/wlpOuRSlUgLPazhhHkWJeKf64k+wfDsnwkGkDE8l1EaPjTyVUFF8kSbY5G
bDd7wpwMgTSo3cOp46TUvDcqwBwTito/JAenUe3lr+tZeLAkXx/efhqB5RzyKipu
2x6SF1AuFiodu/frf88Pp3FSVkMByg1xAJcXWQhkM8QyH/hXET3ELe25uncaSTRa
pXnB86Clkj9N1uqDhy2Ji0fcPZ4Fmj2lLAtT6SU1BDeOvag+otFzEAZ0FsCMcX8m
eQF0XdKNEk9lKUHzYULjjYoB6BGp5/qj94Ldlnsn4EYGRyH87XwB7sVsBAGVB9Xz
xYI+lRFgUMIFVhWizPg3z5E3417XTEUmVm8HchFcjwndkOLm4QLr9KUp9SzN1VSq
qhPg2K/FGB/+Ae87qIV1+/03uqAtUEaaq5pgD97831f83Ex82Yygu+WuLZYz5323
TVs4ash+syddF/hqGx2ux0yLPD0mXv0V2bvmlVnxTqmDE2ONOEZ3le5zL5Cx7bXt
YgPx55H7IlS7XrFPbCH/EBmIqhFcY8TfVyxgpulKYy2qGnRnyPK4SbeC5KHU/fxP
ye8f2i4rBKLTHeNEH381
=5uJk
-----END PGP SIGNATURE-----

**Comment by mtlynch** [comment]
We deployed a new version of mlab-ns yesterday that should fix this. Please let me know if you're still seeing this on your end with mlab-ns.appspot.com.

**Comment by hellais** [comment]
This has not been happening anymore. Closing.
